# Generated by Django 5.0.4 on 2024-04-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets_listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='media',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
