# Generated by Django 5.0.4 on 2024-04-11 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_listing', '0002_remove_pet_media_delete_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.RemoveField(
            model_name='pet',
            name='address',
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='pets_listing.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets_listing.city'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
