# Generated by Django 5.0.4 on 2024-04-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets_listing', '0003_alter_organization_address_remove_pet_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
