# Generated by Django 5.0.4 on 2024-04-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets_listing', '0004_alter_organization_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['created_at'], 'permissions': (('create_organization', 'Can create organization'),)},
        ),
    ]
