# Generated by Django 5.0.4 on 2024-04-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets_listing', '0005_alter_organization_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['created_at']},
        ),
    ]
