# Generated by Django 5.0.4 on 2024-04-21 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_listing', '0006_alter_organization_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='pets_listing.pet')),
            ],
        ),
    ]
