# Generated by Django 5.0.4 on 2024-04-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets_listing', '0007_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='type',
        ),
    ]
